[package]
name = "domain"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
petgraph = "0.8.3"
serde = { workspace = true }
thiserror = { workspace = true }
