[workspace]
members = ["crates/sdk", "crates/macros"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
toml = "0.8"
semver = { version = "1.0.24", features = ["serde"] }
anyhow = "1.0.95"
thiserror = "2.0.9"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
wit-bindgen = { version = "0.36.0", features = ["realloc"] }
