[package]
name = "env-architect"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
domain = { path = "crates/domain" }
infrastructure = { path = "crates/infrastructure" }
application = { path = "crates/application" }
