[package]
name = "notary-worker"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# Workspace
database = { workspace = true }

# System
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenv = { workspace = true }
serde_json = { workspace = true }
uuid.workspace = true
serde.workspace = true
wasmparser = "0.243.0"
sqlx.workspace = true
# sigstore = "0.8" # Will rely on workspace later
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"] }
oci-client = { version = "0.13", default-features = false, features = [
    "rustls-tls",
] }
futures-util = "0.3"
async-trait = "0.1"
